[package]
name = "chip-8_emulator"
version = "1.0.0"
authors = ["Lily Jaroszek <jaroszek0@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[dependencies]
rand = "0.8.1"
rodio = "0.13.0"
chrono = "0.4"

[dependencies.crossterm]
version = "0.19.0"