[package]
name = "emulator"
version = "0.1.0"
authors = ["Jaroszek <jaroszek0@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.1"
rodio = "0.13.0"

[dependencies.crossterm]
version = "0.19.0"